<div class="container">
<div class="jumbotron">
    <h2>用户</h2>
    <div class="container">
        <!--				-->                <!-- 通知列表 -->
        <div class="notice-list" id="J-notice-list">
            <form action="/admin/student/delect" method="post">
                <table class="table">
                    <thead>
                    <tr>
                        <th class="id">序号</th>
                        <th class="orderId">用户名</th>
                        <th class="reportTime">添加日期</th>
                        <th class="orderTitle" style="width: 24%">用户组(悬停查看权限)</th>
                        <th class="dealType">电话</th>
                        <th class="dealPerson">qq</th>
                        <th class="dealPerson">状态</th>
                        <th class="operate">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($user as $row) {;?>
                    <div class="container">
                    <tbody>
                    <!--合并页面  实现数据读取-->
                    <tr data-link="/admin/detailed/detailed?id=<?=$row['id'];?>">
                        <td class="id"><?=$row['id'];?></td>
                        <td class="read">
                            <?=$row['name'];?>								</td>
                        <td class="reportTime"><?php echo date('Y-m-d H:m:s', $row['addTime']); ?></td>

                        <td class="groupName" title=<?php echo "权限：" . $row['access']; ?>> <?=$row['groupName'];?>	 </td>
                        <td class="phone">
                            <?=$row['phone'];?>								</td>
                        <td class="dealPerson"> <?=$row['qq'];?>	 </td>
                        <td class="dealPerson"> <?php if ($row['status'] == 1) {echo "启用中";} else {echo "已禁用";}
    ;?>	 </td>
                        <td><a href="/admin/index/edit?id=<?=$row['id'];?>">编辑</a></td>
                    </tr>
                    </tbody>
        </div>
        <?php ;}
?>

                    </tbody>

                </table>
            </form>
            <div class="pagination ovh">
                <div class="ovh">
                    <?php echo $page; ?>
                </div>
            </div>
        </div>
    </div>
</div>

</div>
