<div class="container">
<h1><td><a href="/admin/index/add">添加</a></td></h1>
<!--<h1><td>--><?php //echo $this->session->get("adminName"); ;;;;;;;;;;;;;;;;;;;;?><!--</td></h1>-->
</div>



<!--				-->                <!-- 通知列表 -->
<div class="container" id="J-notice-list">
    <table class="table">
        <thead>
        <tr>
            <th class="id">序号</th>
            <th class="orderId">用户名</th>
            <th class="reportTime">添加日期</th>
            <th class="orderTitle" style="width: 24%">用户组</th>
            <th class="dealType">电话</th>
            <th class="dealPerson">qq</th>
            <th class="dealPerson">状态</th>
            <th class="operate">操作</th>
        </tr>
        </thead>




        <?php foreach ($user as $row) {
    ;?>
        <div class="container">
            <tbody>
            <!--合并页面  实现数据读取-->
            <tr data-link="/admin/detailed/detailed?id=<?=$row['id'];?>">
                <td class="id"><?=$row['id'];?></td>
                <td class="read">
                    <?=$row['name'];?>								</td>
                <td class="reportTime"><?php echo date('Y-m-d H:m:s', $row['addTime']); ?></td>

                <td class="orderId"> <?=$row['groupName'];?>	 </td>
                <td class="dealType">
                    <?=$row['phone'];?>								</td>
                <td class="dealPerson"> <?=$row['qq'];?>	 </td>
                <td class="dealPerson"> <?php if ($row['status'] == 1) {echo "启用中";} else {echo "已禁用";}
    ;?>	 </td>
                <td><a href="/admin/index/edit?id=<?=$row['id'];?>">编辑</a></td>
            </tr>
            </tbody>
        </div>
            <?php ;}
?>
        <tfoot>
        <tr class="noborder form-inline">
            <td colspan="11" class="left first">
                <span></span>
            </td>
        </tr>

        </tfoot>
    </table>
    <div class="pagination ovh">
        <div class="ovh">
            <?php echo $page; ?>
        </div>
    </div>
    </div>
