<div class="container">
<h1><td><a href="/admin/index/add">添加</a></td></h1>
<!--<h1><td>--><?php //echo $this->session->get("adminName"); ;;;;;;?><!--</td></h1>-->
    <form role="form">
        <div class="form-group">
<?php foreach ($users as $row) {
    ;?>
    <div class="container">
    <tr>
        <td class="option">
            <input name="" class="checkbox" type="checkbox">
        </td>
        <td><strong><?=$row['name'];?></strong></td>
        <td><?=$row['addTime'];?></td>
        <td></td>
        <td><a href="/admin/index/edit?id=<?=$row['id'];?>">编辑</a></td>
    </tr>
    </div>
<?php }
;?>
</div>
</div>
</form>