<h1><td><a href="/admin/index/add">添加</a></td></h1>
<?php foreach ($users as $row) {
    ;?>
    <tr>
        <td class="option">
            <input name="" class="checkbox" type="checkbox">
        </td>
        <td><strong><?=$row['name'];?></strong></td>
        <td><?=$row['addTime'];?></td>
        <td></td>
        <?php $id = $row['id'];
    echo $hr          = "/admin/index/edit?id=" . $id;
    ?>
        <?=$this->tag->linkTo("/admin/index/login", "Search");?>
        <td><a href="/admin/index/edit?id=<?=$row['id'];?>">编辑</a></td>
    </tr>
<?php }
;?>